### ISSUE TITLE
module 'socket.http' not found

### ISSUE THREAD

**Issue by ariefbayu** [leafo/moonrocks-site#29]
Hi There,

I am not sure it this is the right place to ask. If it is not, don't hesitate to close it (after pointing me where is the right place to ask :) ).

Here is the problem: I am trying to run telegram-bot under fresh install of OSX Yosemite. Dependencies are managed by macport. My problem is, as shown in the title, I can't seem to link telegram-bot script to LuaRocks installed luasocket. How should I check or remedy the situation? I am quite new to LUA.

Your kind help is appreciated.

**Comment by leafo** [comment]
Hello, this is the issues tracker for the website that hosts the lua modules. If you're having an issue with the command line tool I suggest opening an issue or sending a message on the luarocks mailing list. Here's the link to the repo: https://github.com/keplerproject/luarocks

You can also try the Lua mailing list for any generic questions. http://www.lua.org/lua-l.html
