### ISSUE TITLE
The LuaRocks docs have vanished!

### ISSUE THREAD

**Issue by rrthomas** [leafo/moonrocks-site#30]
luarocks.org now redirects to rocks.moonscript.org, and I can't find the LuaRocks documentation linked to anywhere. Am I missing something?

**Comment by leafo** [comment]
They are currently living here: https://github.com/keplerproject/luarocks/wiki

We're still working out the details and linking everything together. Sorry for the trouble

**Comment by rrthomas** [comment]
Thanks for the pointer; would it be possible to put a note & link near the top of  the front page of the current luarocks.org?

**Comment by daurnimator** [comment]
> put a note & link near the top of the front page of the current luarocks.org?

:+1:

**Comment by leafo** [comment]
There's now a link on the top
