### ISSUE TITLE
Can't Download Luarock (Vert)

### ISSUE THREAD

**Issue by ElijahCaine** [leafo/moonrocks-site#33]
I have tried downloading the `vert` rock from the moonrocks site but for some reason I get this output:

    $ sudo luarocks install --server=http://rocks.moonscript.org/manifests/luarocks vert
    
    Error: No results matching query were found.

It seems like this rock can't be found on the servers. When I manually search on the moonrocks site it shows up just fine and I am able to download other rocks just fine (I tested by running `luarocks install ao` and that grabbed the `ao` rock just fine.

I can install the `vert` rock just fine from source but now I'm curious why *this* rock is having problems and not others.

**Comment by leafo** [comment]
Appears to be there now. Did you figure out your issue?

**Comment by ElijahCaine** [comment]
@leafo The package is there but I can't install the package through the luarocks cli.

**Comment by leafo** [comment]
What version of lua is your luarocks using? Just run luarocks without any arguments and it's on the bottom.

**Comment by ElijahCaine** [comment]
@leafo This is what that output gives me:

    CONFIGURATION
	Lua version: 5.2
	Configuration files:
		System: /etc/luarocks/config-5.2.lua (ok)
		User  : /home/eli/.luarocks/config.lua (not found)

	Rocks trees in use: 
		/home/eli/.luarocks ("user")
		/usr ("system")

Again, installed another package with the luarocks cli no problem (if you count using `sudo` as not a problem, that's just my installation path which is no biggie).

**Comment by leafo** [comment]
Your version of luarocks is for lua 5.2 but the module is restricted to installing on 5.1 only.

**Comment by ElijahCaine** [comment]
@lefo Ah! Gotcha. I'll upgrade vert for the newest version of lua.

**Comment by leafo** [comment]
Looks like it was done but never uploaded: https://github.com/aconbere/vert/commit/4a5cc38a6b73bdbc68bb58c00be4e9db10180383

The package is currently orphaned on luarocks.org. Maybe @aconbere would like to take it over?

**Comment by ElijahCaine** [comment]
@leafo I can take over that project if we need a maintainer. I just checked the source for vert-0.0.3-2.rockspec and it specifies "lua >= 5.1" as the dependency and things kinda just work with lua 5.2.

**Comment by leafo** [comment]
I'll wait to hear back from the author. I updated the module on the luarocks account on the site so it should install now with no additional work.

**Comment by ElijahCaine** [comment]
@leafo I checked it out, installed without a hitch. Thanks!

**Comment by aconbere** [comment]
@leaf is there anything you still need from me?

**Comment by leafo** [comment]
Hey @aconbere, if you log into http://rocks.moonscript.org and link a github account from the settings page you can automatically take ownership of any lua modules that are part of luarocks. That way when you publish new versions you can upload them directly to you account. Thanks
