### ISSUE TITLE
Solaris 11.2 cannot make bootstrap

### ISSUE THREAD

**Issue by CirrusThink** [leafo/moonrocks-site#37]
It looks like there is an issue with io.popen is it correct that I cant get 
 luarocks install luasql-postgres
Your version of Lua does not support io.popen,
which is required by LuaRocks. Please check your Lua installation.

Are there any possible work arounds ?

**Comment by leafo** [comment]
Sounds like this is an issue with luarocks/lua on your system and not the
luarocks website. I don't have any experience with solaris, so I suggest
posting in the mailing list or issues tracker for either lua or luarocks.

**Comment by CirrusThink** [comment]
Yeah you are correct.
I was able to reinstall LUA 5.2.x from source on Solaris with make solaris && make install which corrected  the issue. Thanks fro respoding
