### ISSUE TITLE
Hosting Architecture

### ISSUE THREAD

**Issue by thefosk** [leafo/moonrocks-site#44]
Because of issue keplerproject/luarocks#338 I tried to investigate a little bit more how rocks are being hosted:

```
$ host rocks.moonscript.org
rocks.moonscript.org has address 54.204.57.69
$ host 54.204.57.69
69.57.204.54.in-addr.arpa domain name pointer ec2-54-204-57-69.compute-1.amazonaws.com.
```

It seems like an EC2 instance is being used, and unless the instance itself is a load balancer, it could be that when it's under load it's not able to serve all the requests.

Without more knowledge of the architecture of the system the following suggestion may be wrong, but how about hosting the rocks on an AWS S3 repo? That would make the system more reliable, it would offload the load balancing to AWS, and could also be replicated in a CDN using AWS CloudFront?

*On a side note the company I work for, Mashape, would be happy to sponsor the project and pay for bandwidth and infrastructure to make sure it's always 100% up and running. We could share a conversation about this at marco@mashape.com*

**Comment by leafo** [comment]
Does this happen regularly. I have a monitor on the server and I don't see any reports of downtime. I can spend some more time looking though.

**Comment by leafo** [comment]
Everything should be okay now
