### ISSUE TITLE
LuaRocks search engine is not working

### ISSUE THREAD

**Issue by tomasguisasola** [leafo/moonrocks-site#46]
The problem could be reproduced by:

1. access the page http://luarocks.org
2. type anything at the field on top of the page (between "LuaRocks" and "Install . Docs . Log In . Register"
3. then type ENTER

It shows a page with an error message:

"...e/luarocks/.luarocks/share/lua/5.1/lapis/db/postgres.lua:88: SELECT * from "users"       where username % 'tomas'
      order by similarity(username, 'tomas') desc
          limit 50
      offset 0
    
ERROR: operator does not exist: character varying % unknown (44)"

**Comment by leafo** [comment]
Thanks, forgot to run migration. It's fixed now.
